package com.zenlauncher.zenmode.coreapi.services

/**
 * Contract for analytics event tracking.
 * Mirrors the public API of the old AnalyticsTracker class.
 */
interface AnalyticsTrackerContract {
    fun trackAppFirstOpen(source: String, device: String)
    fun trackOnboardingStarted()
    fun trackPermissionScreenViewed(permissionType: String)
    fun trackPermissionGranted(permissionType: String)
    fun trackSetupCompleted(timeTakenSec: Int, permissionsGrantedCount: Int)
    fun trackBuddyShareStarted(mode: String)
    fun trackBuddyCodeCopied(mode: String)
    fun trackBuddyCodePasted(mode: String)
    fun trackBuddyConnected(mode: String)
    fun trackDailyScreenTime(minutes: Long)
    fun trackWeeklyScreenTime(minutes: Long)

    // ── Weekly recap ("Zen Week") ──
    /** A week's recap was built and the user notified. [outcome] is "kept" or "missed". */
    fun trackRecapReady(weekStart: String, outcome: String)
    /** [source]: "notification", "home", "settings". */
    fun trackRecapOpened(weekStart: String, outcome: String, source: String)
    fun trackRecapCardViewed(weekStart: String, outcome: String, card: String, position: Int)
    fun trackRecapCompleted(weekStart: String, outcome: String)
    /** [cta]: "invest", "recommit", "reports". */
    fun trackRecapCtaClicked(weekStart: String, outcome: String, cta: String)
    fun trackReportDownloaded(weekStart: String)
    /** [surface]: where the PRO upsell was shown, e.g. "settings_reports". */
    fun trackProUpsellViewed(surface: String)
    fun trackCircleCreated()
    fun trackCircleJoined(via: String)
    fun trackCircleMemberRemoved(byLeader: Boolean)
    fun trackCircleLeft()
    fun trackBuddyToCircleSwitch()
    fun trackCircleLeadershipTransferred(reason: String)
    fun trackCircleReactionSent(type: String)

fun trackScreentimePermissionGranted(permissionType: String)
    fun trackScreentimePermissionDenied(permissionType: String)
    fun trackDailyScreentimeRecorded(date: String, totalMinutes: Long, blockedMinutes: Long, unlockCount: Int, topApps: List<String>)
    fun trackDailyScreentimeViewed(totalMinutes: Long, vsYesterdayDelta: Int)
    fun trackWeeklyScreentimeRecorded(weekStartDate: String, totalMinutes: Long, avgDailyMinutes: Long, vsLastWeekDeltaPct: Int)
    fun trackWeeklyScreentimeViewed(totalMinutes: Long, vsLastWeekDelta: Int)
    fun trackLifetimeScreentimeUpdated(lifetimeTotalMinutes: Long, daysTracked: Long)
    fun trackLifetimeMilestoneReached(milestoneValue: Int)
    fun trackSessionStart(sessionNumber: Int)
    fun trackDay1CheckinCompleted(actionType: String)
    fun trackDay7MilestoneShown()
    fun trackDay7MilestoneEngaged()
    fun trackDay30MilestoneShown()
    fun trackDay30MilestoneEngaged(cumulativeTimeSaved: Long)
    fun trackReengagementPushSent(pushType: String, daysInactive: Long)
    fun trackReengagementPushOpened(pushType: String)
    fun trackGoldTabViewed(entryPoint: String)
    fun trackGoldEarned(goldAmount: Int, triggerReason: String)
    fun trackGoldPurchaseInitiated(amountLocalCurrency: Int, grams: Int)
    fun trackGoldPurchaseCompleted(amount: Int, currency: String, grams: Int, paymentMethod: String)
    fun trackGoldPurchaseFailed(reason: String)
    fun trackGoldPortfolioViewed(portfolioValue: Int)
    fun trackGoldRedeemed(amount: Int, redemptionType: String)
    fun trackZencircleViewed()
    fun trackZencircleJoinedV3(circleSize: Int, circleType: String)
    fun trackZencircleCreatedV3(circleType: String)
    fun trackZencircleInviteSent(channel: String)
    fun trackZencirclePostCreated(postType: String)
    fun trackZencircleReactionAdded(postType: String)
    fun trackZencircleLeaderboardViewed(rank: Int)
    fun trackZencircleChallengeJoined(challengeType: String, durationDays: Long)
    fun trackZencircleChallengeCompleted(challengeType: String)
    fun trackZencircleLeftV3(tenureDays: Long)
    fun trackReferralShareInitiated(channel: String, shareContext: String)
    fun trackReferralLinkShared(channel: String)
    fun trackReferralSignupCompleted(referredByUserId: String)
    fun trackReferralPointsEarned(amount: Int, reason: String)
    fun trackPointsRedeemed(rewardType: String, amount: Int)
    fun trackOnboardingStartedV3(acquisitionSource: String)
    fun trackOnboardingStepViewed(stepName: String, stepNumber: Int)
    fun trackOnboardingPermissionRequested(permissionType: String)
    fun trackOnboardingPermissionGrantedV3(permissionType: String)
    fun trackOnboardingPermissionDenied(permissionType: String)
    fun trackOnboardingGoalSelected(goalType: String)
    fun trackOnboardingCompleted(totalTimeSeconds: Long)
    fun trackOnboardingAbandoned(lastStep: String)
    fun trackHomeSearchOpened(entryPoint: String)
    fun trackHomeSearchQuerySubmitted(queryLength: Int, resultCount: Int)
    fun trackHomeSearchResultClicked(resultType: String, position: Int)
    fun trackHomeSearchNoResults()
    fun trackHomeSearchAbandoned()
    fun trackBlockerEnabled(blockerMode: String)
    fun trackBlockerDisabled(blockerMode: String)
    fun trackBlockerSessionStarted(mode: String, plannedDuration: Long, blockedApps: List<String>)
    fun trackBlockerSessionCompleted(actualDuration: Long)
    fun trackBlockerSessionInterrupted(elapsedDuration: Long, reason: String)
    fun trackBlockedAppAttempt(appName: String)
    fun trackBlockerBypassUsed(justification: String)
    fun trackBlockerStreakAchieved(streakDays: Long)
}
